### PR TITLE
fixed some issues

### PR DESCRIPTION
**Pull request by galanisd**

### CODE REVIEW

**Comment by andmor-** [comment]
Looks good. Released with [r00039](https://github.com/clarin-eric/SPF-SPs-metadata/releases/tag/r00039)

Might take some hours to propagate to all federations

**Comment by galanisd** [comment]
@andmor- 

thanks! Great!

clarin:el (http://inventory.clarin.gr/) i.e. the greek clarin has been redesigned and reimplemented. The new version
was released at the end of May 2021. In the new clarin:el infra a user is already able to log-in with a greek academic account
via the greek AAI  federation (http://inventory.clarin.gr/ -> sign in -> greek academic account ). Each idp of the greek AAI academic federation should release some attributes. Name surname email etc. The most important one is  email ... because in clarin:el username = email. 

For user authentication we use keycloak. For clarin:eric SP Federation in the sign-in form a button will appear...."european academic account" and the whole thing will be similar to the  greek academic account.  The user will be able to select one of the 2000+ IDPs of SPF and then provide his/her credentials. We have one SP for the Greek clarin federation and one for the  clarin:eric SP Federation. Both were created with simplesamlphp and keycloak  interacts with these 2 SPs.  As already said
in clarin:el username = email. If email attribute is not released by an idp then keycloak will throw an exception and the user will
not log-in to clarin.

Is something that we have to do so that the IDPs of the clarin:eric SP Federation release the required attributes?

**Comment by galanisd** [comment]
One more thing 49 IDPs participate in both federations. But I do not think that this is an issue.

**Comment by galanisd** [comment]
@andmor- 

After ~2 days the new metadata have not yet been added to the production xml.
https://infra.clarin.eu/aai/prod_md_about_spf_sps.xml
and they have not been propagated to any IDP; at least the ones I checked.

The metadata have been added here
(Metadata about all CLARIN Service Providers (production and preproduction))
https://infra.clarin.eu/aai/md_about_spf_sps.xml
<md:EntityDescriptor entityID="https://inventory.clarin.gr/samlbridge2/module.php/saml/sp/metadata.php/default-sp">
....

Also in the Centre Registry
https://centres.clarin.eu/spf
I can't find the production entityID "https://inventory.clarin.gr/samlbridge2/module.php/saml/sp/metadata.php/default-sp"
instead the entityID (http://inventory2.dev-clarin.ilsp.gr/samlbridge2/module.php/saml/sp/metadata.php/default-sp)
that I was using for some  tests is listed.

Dimitris

**Comment by andmor-** [comment]
My apologies for the late reaction. I have been migrating my working machine and it's taking some time.

You spotted the problem. The entry in the Centre Registry defines which SPs are propagated. And I forgot to update it.

I have now changed it to the new entityID `https://inventory.clarin.gr/samlbridge2/module.php/saml/sp/metadata.php/default-sp` and marked it as `production`. This should trigger its propagation to all CLARIN federations.

> Is something that we have to do so that the IDPs of the clarin:eric SP Federation release the required attributes?

Not really. We can only really control the CLARIN central IdP (idm.clarin.eu), all other IdPs are controlled by their respective institutions and are always free to release (or not) the necessary attributes. This is one of the main points of the CLARIN SPF, we monitor for CLARIN SP login failures and contact the failing IdP requesting that they start releasing the mandatory attributes to **all** CLARIN SPs (by whitelisting the  ‘clarin-member’ entity category).

The other 2 ECs: R&S and CoCo are verified by the NRENs and the IdPs to comply with our request to release the attributes we need. Still many IdPs have to be explicitly configured for this, as they use a whitelist model.

**Comment by andmor-** [comment]
> One more thing 49 IDPs participate in both federations. But I do not think that this is an issue.

If you have user accounts generated in your system (in keycloak or any application behind the SP) after the 1st successful federated login. This could lead to double accounts in case the user comes in via both federations at some point. 

I am not sure of this since it depends on the architecture:
- is keycloak an AAI proxy SP?
- Do you use the same SAML metadata  and entityID here, as you use in the greek federation?

But I guess we can just try it out and see what happens :)

**Comment by galanisd** [comment]
Ok great. thank for the feedback/info.

> This could lead to double accounts in case the user comes in via both federations at some point

Already tested. It will not create double accounts because we use email as username of the user. 
Keycloak just adds some info that the user X has logged-in via Greek federation and SPF.

> Do you use the same SAML metadata and entityID here, as you use in the greek federation?

Not the same entityID. Also not the same metadata. SPF has some extra specs/requirements.

I do not think that we will have any issues. I described to you the clarin:el authentication architecture/setup just to be sure
that you do not see any significant problems.

It will be great to test and finish the integration of clarin:el with the SPF in the next days/weeks since
we plan to submit for centre B assessment in the next round.

**Comment by andmor-** [comment]
We got the following follow up from DFN-AAI, who inserts the metadata in eduGAIN on behalf of CLARIN:

> I'm afraid we're unable to register https://inventory.clarin.gr/samlbridge2/module.php/saml/sp/metadata.php/default-sp with DFN-AAI because the certificate's Subject doesn't contain a CN. Furthermore, the Privacy Statement URL https://inventory.clarin.gr/site_media/Privacy_Policy.pdf doesn't work

Can you adress these? Let me know if you need any help

**Comment by galanisd** [comment]
A. Fixed Privacy Statement URL. Provided the latest one https://www.clarin.gr/en/content/privacy-policy
B. Spotted an issue with administrative contact person. Changed the name.
C. It seems that simplesamlPHP does not provide a way for adding 
```
<ds:X509SubjectName> CN=....
                        </ds:X509SubjectName>
```
D. Checked webanno's spf metadata. Do we also need 
`<ds:KeyName>webanno.sfs.uni-tuebingen.de </ds:KeyName>`? If yes then we have the same issue with C.

I searched a little bit for C and D and it seems that other simplesamlPHP SPs have the same issue for DFN-AAI.
Can I add the requested info manually? It seems that other SPs did the same thing.

I will wait your answers before push->pull request etc.

**Comment by andmor-** [comment]
Thanks for the fixes.

I am not sure what you mean. Webanno's certificate (entityID="https://webanno.sfs.uni-tuebingen.de") does provide CN. When I decode their certificate I can read: `Common Name: webanno.sfs.uni-tuebingen.de` 
This information is indeed missing in your certificate. You can verify this with the following command `openssl x509 -in certificate.crt -text -noout`

So this is not about the XML (where in fact you can add extra information by hand *) but about the information encoded in the x509 certificate. You must provide a CN when generating a certificate. And then as an extra step, indeed also add it by hand to the XML.

Please let me know if I can assist you with any of this.

*The metadata file provided by simpleSAMLPHP is for reference and does not have to be exactly the one you share with the IdPs to setup trust. Though some values e.g. the certificates must match.

**Comment by galanisd** [comment]
Yes I regenarated the certificate and provided a CN and verified it ...  

```
 openssl x509 -in samlspf.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            07:91:49:be:db:37:20:5e:54:da:b8:3d:49:c7:62:56:5e:e7:8e:8c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = inventory.clarin.gr
        Validity
            Not Before: Jul 29 14:50:42 2021 GMT
            Not After : Jul 29 14:50:42 2031 GMT
        Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = inventory.clarin.gr
        Subject Public Key Info:
```


>  And then as an extra step, indeed also add it by hand to the XML.

This is what I wanted to confirm.

I had a look into various metadata files (e.g. webanno) and it seems that except ds:X509SubjectName they also
have ds:KeyName. Do we need it?

**Comment by andmor-** [comment]
There is another issue related with A. To comply with the eduGAIN CoCo you must provide a reference to the CoCo in your privacy policy. This reference should set this exact link: "http://www.geant.net/uri/dataprotection-code-of-conduct/v1"


From the CoCo document itself (point 2.h.g):
```
The Service Provider agrees and warrants: 
...
h) [Information duty towards End User] to provide to the End User, at least at first contact, in an easily, 60 
directly and permanently accessible way a Privacy Policy, containing at least the following information: 
...
   g. a reference to this Code of Conduct;  
```

See any existing privacy policy from our SPs e.g. https://catalog.clarin.eu/privacy_statement.xhtml

**Comment by andmor-** [comment]
> I had a look into various metadata files (e.g. webanno) and it seems that except ds:X509SubjectName they also
have ds:KeyName. Do we need it?

I don't think so. But we will soon find out :)

**Comment by galanisd** [comment]
So if we add a section


**Data Protection Code of Conduct**

"Personal data will be protected according to the **GÉANT Data Protection Code of Conduct** for Service Providers, a common standard for the research and higher education sector to protect the user's privacy."

with a link to "http://www.geant.net/uri/dataprotection-code-of-conduct/v1" then we will be ok

???

**Comment by andmor-** [comment]
I believe yes.

**Comment by galanisd** [comment]
added CN, fixed privacy policy url, privacy policy document also now contains http://www.geant.net/uri/dataprotection-code-of-conduct/v1. I created a new pull request

**Pull request merged**
