### PR TITLE
Change blinky.ukp to sp.ukp

### PR DESCRIPTION
**Pull request by jcklie**
We decided to move our SP to a dedicated VM, therefore we need to update the metadata. I just changed the key and URIs.

### CODE REVIEW

**Comment by jcklie** [comment]
I dont understand why the diff looks so noisy

**Comment by andmor-** [comment]
Login using the CLARIN IdP went trough without a problem.
Note: this is still only available on the CLARIN IdP (staging feed).

**Comment by jcklie** [comment]
Thank you! We are working on the legal document, sorry for the delay.

**Comment by andmor-** [comment]
No problem. This can wait!

**Pull request merged**
