### PR TITLE
added privacy statement

### PR DESCRIPTION
**Pull request by galanisd**

### CODE REVIEW

**Comment by andmor-** [comment]
The privacy policy does not seem to contain a link to the GÉANT Data Protection Code of Conduct. This is an hard requirement to the attribution of the CoCo EC.

See https://geant3plus.archive.geant.net/uri/dataprotection-code-of-conduct/V1/Documents/GEANT_DP_CoC_ver1.0.pdf specifically point 2 section h)

Can you also update your base branch for this PR?

**Comment by andmor-** [comment]
What's the current timeline to reach production?

I see your entityID has "dev" on it. While this is technically allowed in production, some IdPs might not like to talk to "dev" SPs so maybe you want to change this meanwhile?

Note that the entityID is just an ID and does not have to match any existing URL.

**Comment by galanisd** [comment]
> The privacy policy does not seem to contain a link to the GÉANT Data Protection Code of Conduct.

I thought that this was enough ... 
https://github.com/APOLLONIS/SPF-SPs-metadata/blob/master/metadata/inventory2.dev-clarin.ilsp.gr%252Fsamlbridge2%252Fmodule.php%252Fsaml%252Fsp%252Fmetadata.php%252Fdefault-sp.xml#L6

It is not?

**Comment by andmor-** [comment]
That is not really up to us. We can declare it, but the CoCo entity attribute is assigned to our SPs based on the federations' assessment of the SP.
In this case for CoCo. They will check if your SP fulfills all the conditions written in the [CoCo itself](https://geant3plus.archive.geant.net/uri/dataprotection-code-of-conduct/V1/Documents/GEANT_DP_CoC_ver1.0.pdf) if not they won't propagate that attribute.

**Comment by andmor-** [comment]
The federations' automatic check for CoCo compliance, checks if the string `http://www.geant.net/uri/dataprotection-code-of-conduct/v1 ` is mentioned in the document URL  you supply via: mdui:PrivacyStatementURL

**Comment by andmor-** [comment]
you can draw inspiration from e.g. https://catalog.clarin.eu/privacy_statement.xhtml for entityID=`"https://sp.catalog.clarin.eu"`

**Comment by galanisd** [comment]
> What's the current timeline to reach production?

ASAP, for example, in the next 2-3 weeks

> I see your entityID has "dev" on it. While this is technically allowed in production, some IdPs might not like to talk to "dev" SPs so maybe you want to change this meanwhile?
> 
> Note that the entityID is just an ID and does not have to match any existing URL.

The entityID value is auto-generated. Currently I am working on a dev instance of CLARIN, however, I was planning
to deposit metadata only for the production instance. This means that the last step will be to 
change the URLs in the xml to the ones that are for the production instance. 

Based on this report (https://clarin-eric.github.io/SPF-SPs-metadata/web/sp_qa_report.html?inventory2.dev-clarin.ilsp.gr%2Fsamlbridge2%2Fmodule.php%2Fsaml%2Fsp%2Fmetadata.php%2Fdefault-sp_sps_qa_report_results.xml)
our metadata right now are in a pretty good shape. We have only five yellow issues (no red ones).  
Two of them are (no 3,4) are I think because we use http rather than https. Right?
This of course will be corrected in the final production xml.

The other 3 yellows cannot be corrected I think. We use simplesamlphp for creating the SAML SP metadata and invested quite some time to integrate simplesamphp with the rest of system. simplesamlphp seems that it does not provide a way to add a RequestInitiator and different keys
(Duplicate keys ‘//ds:X509Certificate’ found. Counted only 1 distinct keys among 2 keys.) I will double check.

Of course we will take care the CoCo compliance issue.

So the final xml will probably generate the aforementioned 3 warnings. Is this OK? We have already tested the whole setup
by adding the SP metadata to our IDP (https://idp.athenarc.gr/) and it works as expected.

**Comment by andmor-** [comment]
The planning sounds good. Let's merge first to generate a new report....

**Comment by andmor-** [comment]
> Two of them are (no 3,4) are I think because we use http rather than https. Right?

Yes. For `SingleLogoutService` we could let it be but for `AssertionConsumerService` an https endpoint is a must. Since some IdPs do not support SAML encryption this information whould flow totally unencrypted.

> (Duplicate keys ‘//ds:X509Certificate’ found. Counted only 1 distinct keys among 2 keys.) I will double check.

It's OK. The warning suggests you do not need to specify the same key twice. Just use one `KeyDescriptor` element wthout the `@use` attribute.

The first two points are not really a problem.

My concern here is about testing against IdPs from the federations. As it is, I think that to propagate this to the federations, all we need is the CoCo and then we can start testing. But we should go immediately with the final entityID. To avoid registering multiple SPs.

Note: I am not sure about your system details, but the metadata you deposit here does not need to textually match the one your system generates. So you can do manual changes on the metadata you advertise here for propagation.
e.g. You could only use one certificate declaration here (as suggested above) but your simplesamlphp would still generate its SAML with 2 declarations. As long as the certificate configured in your simplesamlphp matches the one you publish here, it will work.

**Comment by galanisd** [comment]
> The planning sounds good. Let's merge first to generate a new report....

As expected I get the same errors. I will talk with my colleagues in order to fix the issue with 
the  CoCo compliance ASAP.

Please tell me ASAP if the other issues that are mentioned are a problem? It is very important.
We should we ask Dieter for this?

**Comment by andmor-** [comment]
we probably crossed messages... did I answer your questions above?

**Comment by galanisd** [comment]
yes we posted at the same time.

> My concern here is about testing against IdPs from the federations. 

How we will test? Do you have access to many IDPs? Or you ask from other users to do it?

> As it is, I think that to propagate this to the federations, all we need is the CoCo and then we can start testing. But we should go immediately with the final entityID. To avoid registering multiple SPs.

I will take care these asap.

**Comment by galanisd** [comment]
Note: I am not sure about your system details, but the metadata you deposit here does not need to textually match the one your system generates. So you can do manual changes on the metadata you advertise here for propagation.
e.g. You could only use one certificate declaration here (as suggested above) but your simplesamlphp would still generate its SAML with 2 declarations. As long as the certificate configured in your simplesamlphp matches the one you publish here, it will work.

**Comment by galanisd** [comment]
> Note: I am not sure about your system details, but the metadata you deposit here does not need to textually match the one your system generates. So you can do manual changes on the metadata you advertise here for propagation.
> e.g. You could only use one certificate declaration here (as suggested above) but your simplesamlphp would still generate its SAML with 2 declarations. As long as the certificate configured in your simplesamlphp matches the one you publish here, it will work.

Ok this solves the issues very quickly.

**Comment by andmor-** [comment]
> How we will test? Do you have access to many IDPs? Or you ask from other users to do it?

I can test from the University of Utrecht and from EGI. Then we can ask our colleagues at other CLARIN centres to try with theirs.

Ideally at this point we would already be using the final entityID. This could be a problem because the entityID has to match, so if your SP is running on a `-dev` domain, and its configured entityID is always bound to the URL it runs on, as I understood from above, we won't be able to test using the final entityID.

**Comment by galanisd** [comment]
> Ideally at this point we would already be using the final entityID. This could be a problem because the entityID has to match, so if your SP is running on a -dev domain, and its configured entityID is always bound to the URL it runs on, as I understood from above, we won't be able to test using the final entityID.

Good point! Many thanks for your suggestions! I think that I have a solution for this. I will create an SP that will have the final entityID and URLs and will be deployed in the correct/final location. E.g. http://inventory.clarin.gr/samlbridge2/module.php/saml/sp/metadata.php/default-sp
It will be like being in production.

**Pull request merged**
