### PR TITLE
EntityDescriptors for DELT and DELT dev service added to the Austrian Academy (CLARIN-AT)

### PR DESCRIPTION
**Pull request by dpancic**
EntityDescriptors for the Database of English Learner Texts (DELT) and DELT dev service are added to the Austrian Academy (CLARIN-AT)

### CODE REVIEW

**Comment by andmor-** [comment]
As it is, this cannot be merged into production.

The privacy policy does not contain a link to the GÉANT Data Protection Code of Conduct. This is an hard requirement to the attribution of the CoCo EC.
Please see, point 2 section h) of: https://geant3plus.archive.geant.net/uri/dataprotection-code-of-conduct/V1/Documents/GEANT_DP_CoC_ver1.0.pdf

Also you can use other ACDH SPs as inspiration: https://arche.acdh.oeaw.ac.at/browser/privacy seems to have a fairly complete privacy policy for CoCo attribution.

**Comment by dpancic** [comment]
Thank you
Link to the GÉANT Data Protection Code of Conduct is added to both PrivacyStatementURL's.
Please see https://delt.acdh.oeaw.ac.at/terms-of-use/ and https://delt.acdh-dev.oeaw.ac.at/terms-of-use/

**Comment by andmor-** [comment]
Looks good!
Can you confirm that it is OK for you if we propagate the production SP to eduGAIN and all CLARIN countries, but leave the "dev" one only at the SPF level. i.e. working only against our central IdP? It might be a bit more difficult to propagate a "dev" SP to eduGAIN and the federations.

**Comment by csae8092** [comment]
Hi @andmor- SPF level is totally fine for dev version. Thank you!

**Comment by andmor-** [comment]
Merged into production.
The system will pick this up in about one hour and propagation to eduGAIN and national federations will follow.

Is there a federated login URL we can use to test the SPs against our central IdP?

**Comment by csae8092** [comment]
https://delt.acdh.oeaw.ac.at/Shibboleth.sso/Login
https://delt.acdh-dev.oeaw.ac.at/Shibboleth.sso/Login

**Comment by andmor-** [comment]
Currently on our IdP only.

On "dev": the CLARIN central IdP seems to work with it, but asks to login again when clicking "Explore the Data"
On "prod": the CLARIN central IdP seems to work but when clicking "Explore the Data" I get a browser native alert: "FATAL - DISCO UI:No URL return parameter provided"

Do you have an account on the CLARIN IdP to check this?

**Comment by csae8092** [comment]
Due to our server set up I still need rewrite parts of the library I use to hook our django-based service to shibboleth. I'll give you notice when it works (which will hopefully soon...). But as far as I can tell by now, your side of the job is done.

**Comment by andmor-** [comment]
OK. Let me know when it is working so we can propagate the production SP to eduGAIN and the national federations.

**Comment by csae8092** [comment]
From our site everything works now as it should

**Comment by andmor-** [comment]
Pushing it to DFN-AAI, I received the following:

> Dear colleagues,
> the PrivacyStatemanetURL for https://delt.acdh.oeaw.ac.at/shibboleth (i.e. https://delt.acdh.oeaw.ac.at/terms-of-use/) contains a wrong reference to the Code of Conduct for Service Providers:
> https://geant3plus.archive.geant.net/uri/dataprotection-code-of-conduct/v1/Pages/default.aspx
> 
> The correct URL is http://www.geant.net/uri/dataprotection-code-of-conduct/v1, please refer to https://wiki.refeds.org/display/CODE/Entity+Category+Definition%3A+Data+protection+Code+of+Conduct

Can you fix it?

**Comment by csae8092** [comment]
fixed it, thanks for noticing!

**Pull request merged**
