### PR TITLE
Adds additionals metadata

### PR DESCRIPTION
**Pull request by cyrilpestel**

### CODE REVIEW

**Comment by cyrilpestel** [comment]
Hi,

I have an issue with the RequestInitiator and DiscoveryResponse element. We uses Keycloak for managing users and IdPs. The login page needs url parameters (e.g client_id, redirect_uri, ...) but the XML Attribute (Location) don't allow the "&" character. When I change it by "&amp;" the url is not valid cause of the missing parameters. The web browser don't replace the "&amp;" special character.

Do you have an idea on how to manage it ?

**Comment by andmor-** [comment]
Have you tried to escape the `&` with `&amp;` ?

**Comment by cyrilpestel** [comment]
Yes, the XML is correct by the final url is not the same. The web browser don't replace &amp; by &.

https://demo-auth.ortolang.fr/auth/realms/ortolang/protocol/openid-connect/auth?client_id=market&redirect_uri=https%3A%2F%2Fdemo.ortolang.fr%2F&state=86120e98-6e55-4c60-8b6e-8073e3306cdb&response_mode=fragment&response_type=code&scope=openid&nonce=31e7f42a-6bd0-4bbe-9342-27bf59dd78d3&kc_locale=fr

https://demo-auth.ortolang.fr/auth/realms/ortolang/protocol/openid-connect/auth?client_id=market&amp;redirect_uri=https%3A%2F%2Fdemo.ortolang.fr%2F&amp;state=86120e98-6e55-4c60-8b6e-8073e3306cdb&amp;response_mode=fragment&amp;response_type=code&amp;scope=openid&amp;nonce=31e7f42a-6bd0-4bbe-9342-27bf59dd78d3&kc_locale=fr

**Comment by andmor-** [comment]
I am not sure what is your intended setup. In SAML for SP initiated SSO, the SP passes the necessary data in a SAML payload to the user's browser (not in the URI parameters) and this should work for any SAML IdP (not only for https://demo-auth.ortolang.fr). This way `RequestInitiator` and `DiscoveryResponse` (which are SP attributes) never have parameters as much as I am aware.

We can try to configure your SP with the base URL only `https://demo.ortolang.fr/` ? And see if this continues on working with the CLARIN central IdP. 

I see that login via `https://demo-auth.ortolang.fr` is currently working and not via SAML, so I don't think adding this values to your distributed SAML metadata will change anything for your own IdP.

**Comment by andmor-** [comment]
Some extra points:
- I can't find anything stating if Keycloak supports [SAML SP Request Initiation Protocol ](https://wiki.oasis-open.org/security/RequestInitProtProf)or not. If not, you should actually not declare `RequestInitiator`
- `DiscoveryResponse` is not needed as the SP (here: https://demo-auth.ortolang.fr) is implementing its own discovery service ([see point 9 of our guidelines](https://www.clarin.eu/content/guidelines-saml-metadata-about-your-sp))
- Finally I cannot conclude from your tests that the `&amp;` won't be decoded in a SAML login flow. while it is true that the browser does not decode this, the URL is crafted by the selected 3rd party IdP before being sent to the users' browser. A proper IdP implementation should decode the `Location` value at that point as it knows it got it from a XML source.

**Comment by cyrilpestel** [comment]
I misunderstood the `RequestInitiator` and `DiscoveryResponse` because I thought it was the login page URL. You're right, Keycloak implements its own discovery service from the login page. So I guest I don't need this two elements.

Do I need to do something more ? something to add to the metadata ?

This was the demonstration environment of the platform. In a few weeks, I will provide for the production.

**Comment by andmor-** [comment]
> Do I need to do something more ? something to add to the metadata ?

No. From what I see and can test everything is good.

> This was the demonstration environment of the platform. In a few weeks, I will provide for the production.

OK so we won't propagate this one to eduGAIN or the national federations. This one will stay in our staging environment, meaning that it only works with the CLARIN IdP.

**Comment by andmor-** [comment]
Released to the CLARIN IdP in [r00033](https://github.com/clarin-eric/SPF-SPs-metadata/releases/tag/r00033).

**Comment by cyrilpestel** [comment]
In fact, the demonstration platform is already in the EduGain through our National Federation because we use this platform to make presentation in any conference. People likes to see how easy it is to log in and upload files before a publication on the front page.

**Comment by andmor-** [comment]
That's good to know. We have to discuss this in order to avoid propagation classes.

Do you intend to use "Fédération Éducation-Recherche" or "CLARIN" to propagate the future non-demo SP to eduGAIN?

You can choose but when using the French federation you have to keep in mind that metadata updates (as when your certificate expires) have to be communicated to both: "Fédération Éducation-Recherche" and "CLARIN". When we propagate to eduGAIN ourselves you just have to communicate it to us.
You also have to ask "Fédération Éducation-Recherche" to add the "clarin-member" "R&S" and "CoCo" entity categories to your metadata.

Some Federations have a low opt-in rate for eduGAIN (e.g. SURFconext) or their IdPs typicaly implement a whitelist after eduGAIN (e.g. DFN-AAI). We will always propagate your metadata to these federations (ACOnet AT, DFN-AAI DE, Belnet BE, SURFconext NL)
The main purpose of the CLARIN SPF is that members help each other to bypass these limitations. This is why it is important to add "clarin-member" entity category, because whitelisting is already done  by many IdPs based on it.

See [this answer](https://github.com/clarin-eric/SPF-SPs-metadata/pull/39#issuecomment-397646491) (the section about  ‘clarin-member’ EC) for more details.

**Comment by cyrilpestel** [comment]
At first, we have join the EduGain by our National Federation (RENATER) because we thought this was the right way to become CLARIN Center B. This is always our goal and if we have to remove the link to EduGain from our National Federation in order to join EduGAIN from CLARIN, this will not be a problem for us.

So I will contact our National Federation to remove the link to EduGAIN and I will send you a message when it's done.

**Comment by cyrilpestel** [comment]
I have unlink to the EduGain by our National Federation (RENATER). But our SP is always in the list of [SP monitored](https://monitor.edugain.org/coco/?f_id_sp=4432&f_entityID=ortolang&page=1&f_order=ts+desc&show=list_sp_tests&f_is_changed=1).

Nevertheless, I guest it is ok to propagate the metadata from the CLARIN federation.

**Comment by andmor-** [comment]
Great. You can opt by using RENATER. But that gives you extra work when you need to update the metadata. So I think things are easier this way.

If you unlinked from RENATER, as soon as we propagate your SP to our production platform, it will appear as registered by DFN-AAI in https://technical.edugain.org/entities. It will always appear in the CoCo monitoring list which is a good thing.

Do you want to propagate this `demo-` SP meanwhile or you have the production one ready?

**Comment by cyrilpestel** [comment]
We are not ready for the production one. But I hope to work on it the next week but I think you can propagate the demo SP.

Thank you for all.

**Comment by andmor-** [comment]
The SP has been propagated and is now visible again in edugain with the following info:
`Registrar: DFN-AAI Org: CLARIN ERIC`

See: https://technical.edugain.org/entities

**Pull request merged**
