### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by galanisd**
fixed privacy policy url, privacy policy doc contains now Data Protection Code of Conduct link,
added CN,

### CODE REVIEW

**Comment by andmor-** [comment]
Released in [r00040](https://github.com/clarin-eric/SPF-SPs-metadata/releases/tag/r00040).

**Comment by andmor-** [comment]
@galanisd can you address the following comment we received from DFN-AAI. We need `mdui:InformationURL` for R&S. R&S is very important for CLARIN SPs
﻿
> If this SP is supposed to be assigned to the R&S Entity Category, a mdui:InformationURL is required, cf. https://refeds.org/category/research-and-scholarship, section 4.3.3.

**Comment by galanisd** [comment]
@andmor- 

Sorry for the late reply. I was on vacation for some days.
I added mdui:InformationURL  element. I used "https://www.clarin.gr/en" as value which leads to
the clarin:el portal. I think similar URLs are used by other SPs

https://github.com/APOLLONIS/SPF-SPs-metadata/blob/master/metadata/inventory.clarin.gr%252Fsamlbridge2%252Fmodule.php%252Fsaml%252Fsp%252Fmetadata.php%252Fdefault-sp.xml

If you think that it is ok I will create a pull request.

**Comment by galanisd** [comment]
One question

image

It seems that  DFN-AAI has "accepted" our metadata. Actually all federations have accepted them except Belnet. 
Do we have any feedback from them?

**Comment by galanisd** [comment]
@andmor- 

any updates on my previous comments/questions?

**Comment by andmor-** [comment]
@galanisd my apologies as I am currently on vacation.

As much as I can see, the SP as been "accepted" but the R&S entity category was not assigned to it (as reported by DFN-AAI), [see](https://met.refeds.org/met/entity/https%253A%252F%252Finventory.clarin.gr%252Fsamlbridge2%252Fmodule.php%252Fsaml%252Fsp%252Fmetadata.php%252Fdefault-sp/?federation=edugain). This EC is important for the IdPs to trust your SP. Despite the fact that the federations have already included your metadata in their feeds, most IdPs have the last word on the SPs they choose to trust.

So yes, make the PR you mentioned and we will merge it as soon as possible. After that DFN-AAI will assign the EC and propagate it downstream.

Regarding Belnet. Propagation to Belgium is still a manual step and we did not proceed with it because we were waiting for this change. I will also push that one at the earliest opportunity.

**Comment by galanisd** [comment]
@andmor- 

https://github.com/clarin-eric/SPF-SPs-metadata/pull/246

**Pull request merged**
