### PR TITLE
added missing values

### PR DESCRIPTION
**Pull request by MicheleMallia**

### CODE REVIEW

**Comment by MicheleMallia** [comment]
Why it's still open?

**Comment by andmor-** [comment]
At first sight:
- the "technical" contact is missing. (the report mentions "support" but that is a known bug)
- the provided contacts need to be real
- since you are using the same certificate for both encryption and signing, you can declare it only once and remove the `use=` attribute. Check the other SPs for examples.
- you can ignore the other warnings

**Comment by MicheleMallia** [comment]
Hi,
I've just update the contact section. I've put my personal number because I've not a office number.So, there is no problem if there is a red flag for "technical" contact missing (if it's a bug...).I use simplesamlphp to generate the saml metadata so I can't change the saml file (I've tried to remove some statements but the duplicate it's still here).I hope this saml file can be right.In the future I'll update with some fixed info (about privacy, logo etc...). 
Thanks.

**Comment by andmor-** [comment]
From a technical point of view this is not a problem. Your simplesamlphp does not have to hold these metadata values. Only `entityID`, the certificate and the assertion consumer service(s) must match. The rest is administrative data for the federations. Also for the contacts, we do not require phone number, but email adreesses yes.

**Comment by andmor-** [comment]
This is just a XML file telling the IdPs how to communicate with your SP. The file in your SP does not have to match (or even exist). Your SP needs however to use the certificate and respond in the URLs it advertises. In that sense this configuration file is to be consumed by IdPs and if something, the syntax should match what IdPs use.

**Comment by MicheleMallia** [comment]
Ok, I Will edit the XML file according to your suggestions. Thanks.

Il lun 22 lug 2024, 18:54 André Moreira ***@***.***> ha
scritto:

**Pull request merged**
