### PR TITLE
OTA changes from move to LLDS in linguistics

### PR DESCRIPTION
**Pull request by jpnp**

### CODE REVIEW

**Comment by andmor-** [comment]
Please update file name according to the instructions in this repository front page for new SPs (also applies to new entityIDs):
```2. ... new file following the same naming convention: [New SP File Name] = [SP entityID].replace("http(s)?://", "").replace("/", "%2F") + ".xml"```

**Comment by jpnp** [comment]
entityID="https://llds.ling-phil.ox.ac.uk/shibboleth"

File is named "llds.ling-phil.ox.ac.uk%2Fshibboleth.xml"

I think that's right?

Thanks,
John

**Comment by andmor-** [comment]
Yes. My bad. Merged, lets see what the QA bot says... it should comment on this issue in about 10mins after merge

**Comment by andmor-** [comment]
All good. You can ignore the warning about "description" length. 

Released with [r00092](https://github.com/clarin-eric/SPF-SPs-metadata/releases/tag/r00092)

Since this is a new entityID might take some 24h to propagate.

You can follow the propagation status across federation here: https://centres.clarin.eu/spf

**Pull request merged**
