### PR TITLE
add LAP metadata

### PR DESCRIPTION
**Pull request by oepen**
hi,

we would like to enable authentication against the CLARIN IdP, hence would be grateful if you could pick up the metadata for our SP (the UiO Language Analysis Portal, built as part of the national CLARINO initiative).

with thanks in advance, oe

### CODE REVIEW

**Comment by andmor-** [comment]
There is already one entry for entityID="https://lap.clarino.uio.no/simplesaml/module.php/saml/sp/metadata.php/default-sp". Please see line 7673. Having two entries with the same entityID is not possible. Should the old entry be updated/replaced instead?

Also mind that committing to this file has further implications than just enabling authentication against the CLARIN IdP. The metadata will ultimately be propagated to eduGAIN and thus to all European IdPs who load SP metadata from eduGAIN.

**Comment by oepen** [comment]
thanks for the quick follow-up!

i am sorry, i had not noticed the old entry was still there.  i recall
uploading it a couple of years ago, but it triggered some compliance
issues back then and for all i know was never moved into production.
thus, i had assumed it had just been purged from the file in the
meantime.  when trying authentication against the CLARIN IdP
yesterday, i was getting

eu.unicore.samly2.exceptions.SAMLRequesterException: Issuer is not
among trusted: https://lap.clarino.uio.no/simplesaml/module.php/saml/sp/metadata.php/default-sp

but today things look better; it appears my SP can (almost)
successfully talk to the CLARIN IdP.  however, i seem to not be
receiving the ‘mail’ attribute, which is the one attribute we really
need:

Backtrace:
0 /etc/httpd/simplesamlphp-1.13.2/www/authmemcookie.php:114 (N/A)
Caused by: Exception: The user doesn't have an attribute named 'mail'.
This attribute is expected to contain the username.

more high-level, yes, the new entry should supersede the old one;
hopefully our metadata will now pass all compliance tests on your end
:-).  do you want me to generate a new pull request, or will you just
merge appropriately?

we are already ‘connected’ to eduGAIN, where i believe our SP metadata
is propagated upstream via the norwegian feide federation.  but i
reckon another path of metadata propagation via CLARIN can only be a
good thing.

best wishes, oe

**Comment by andmor-** [comment]
I replaced the old entry with the new one but the QA assessment is not good enough. [see here](https://clarin-eric.github.io/SPF-SPs-metadata/page/master_qa_report.html)
I created a new branch `lap_clarino` and a PR addressing most of these problems: see #40  

Before proceeding, please read and follow as strictly as possible [our metadata guidelines](https://www.clarin.eu/content/guidelines-saml-metadata-about-your-sp) 

Critical problems:
1. No CoCo entity category -> Fixed
2. No "research-and-scholarship" entity category -> Fixed
3. Logo URL is broken and it is not "https://" scheme -> Must be fixed on your side. Please fork and commit fixing changes to the "lap_clarino" branch.
4. Missing `@isRequired` for some requested attributes -> Fixed
5. Missing `mailto:` in contacts' email addresses -> Fixed

Changes tackling non-critical problems:
1. Reduced English description length.
2. Removed one certificate entry (same certificate is used for both signing and encryption, so there is no need for separate entries).

Please validate my changes and address the logo issue.

According to https://technical.edugain.org/entities , you are in fact already publishing your metadata to eduGAIN via FEIDE. This situation is not ideal and can lead to clashes, plus this way your SP does not get the `clarin-member` EC. Would it be possible for you to request FEIDE not to push your SP to eduGAIN? We will do that ourselves via DFN-AAI.

**Comment by oepen** [comment]
thanks, i will have another go over our metadata :-).

my problem, however, is that the XML is auto-generated from SimpleSAMLphp,
i.e. for each case i need to find the right way to make the correponding
change in the native PHP configuration.  i must confess i recall feeling
somewhat disheartened by this (partly trial-and-error) process last time i
committed our metadata to the CLARIN repository ...

QA-wise you guys in general seem stricter than the average :-).  for
example, my SP appears to receive a clean bill of health on ‘
https://technical.edugain.org/entities’, including CoCo-related
information.  so, i guess, one motivation for me to continue to work
towards full CLARIN QA compliance would be the prospect of gaining the
‘clarin-member’ EC, right?

via FEIDE, i recall we gained the REFEDS entity category.  would we still
have that if our metadata was published via CLARIN (via DFN-AAI) only?

—unrelated to the above (i assume), do you have an idea why our SP is not
(yet) receiving the ‘mail’ attribute from the CLARIN IdP?

with thanks in advance, oe

**Comment by andmor-** [comment]
> QA-wise you guys in general seem stricter than the average :-). for example, my SP appears to receive a clean bill of health on ‘ https://technical.edugain.org/entities’, including CoCo-related information

The CoCo and R&S ECs are indeed present in eduGAIN, perhaps FEIDE added it? The version you supplied to us does not have them... though we also added them in the proposal done #40 :)
Also notice that the `mailto:` warning is shown by the edugain page!

> so, i guess, one motivation for me to continue to work towards full CLARIN QA compliance would be the prospect of gaining the ‘clarin-member’ EC, right?

Kind of. We do not forbid other entities to add this EC for CLARIN SPs. FEIDE could also add this. The motivation is that we do have agreements with multiple national federations allowing us to bypass eduGAIN and thus have full IdP coverage. This is important in countries with low eduGAIN coverage, or where IdPs do white/blacklisting of eduGAIN SPs. Prominent cases are: Belgium, Netherlands, Austria, Czech Republic, Portugal and Germany, where via eduGAIN you get low or no coverage out-of-the-box at all. See: https://technical.edugain.org/isFederatedCheck/Federations/ but remember that even when an IdP is in eduGAIN they can still use black or whitelisting for the SPs they accept. 
If you propagate you metadata only via FEIDE  to eduGAIN, you will have the coverage problem and to talk with some IdPs case by case (which we do in a regular basis). If you propagate via both, you break our workflow (ingest SP metadata in: eduGAIN+low coverage national federations) and create an exception for your SP, which we are not willing to do.
For more info about this, check our wiki pages: https://trac.clarin.eu/wiki/ServiceProviderFederation/DistributionMatrix and https://trac.clarin.eu/wiki/ServiceProviderFederation (let me know if you need an account)

> via FEIDE, i recall we gained the REFEDS entity category. would we still have that if our metadata was published via CLARIN (via DFN-AAI) only?

Yes. All our SPs have it, verified and pushed to eduGAIN by DFN-AAI. You can use the same tool and select the "clarin-member" EC to see all other CLARIN SPs.

> unrelated to the above (i assume), do you have an idea why our SP is not (yet) receiving the ‘mail’ attribute from the CLARIN IdP? 

Not really. We are in fact releasing the `mail` attribute as you can check by logging in here: https://catalog.clarin.eu/secure/shib_test.pl plus many other SPs (including at clarino) use it!
Anyway I think is is better to first sort out the metadata and then we can chase that problem.

**Comment by andmor-** [comment]
Also if FEIDE is indeed adding these ECs to your metadata in edugain, we can just do the same and you do not need to change the auto-generated from SimpleSAMLphp. Although I reckon it would be cleaner specially for the `mailto:` and certificate changes.

**Comment by oepen** [comment]
warmest thanks for the in-depth follow-up and additional background; much
appreciated!  until now, i had not fully appreciated the coverage issues
related to different national eduGAIN practices and, correspondingly, the
prospective benefits of being part of the CLARIN SPF.

you are right, though i had forgotten about it: the CoCo and REFEDS
categories we ‘gained’ by virtue of Feide adding them to our metadata (i
believe they might have required us to submit some kind of paperwork for
that).  before switching over from Feide to CLARIN as our metadata
publisher, i would like to discuss this move with the Feide folks.

one aspect that makes me slightly nervous about this is the opt-in
requirement that applies in norway (and, i believe, some other countries):
as Feide picks up information about a new SP, they announce it to all their
customers.  before users at another norwegian university actually get to
authenticate (via Feide) for the service, their institution needs to
consent.  i would expect the same must be true for non-norwegian SPs (that
support eduGAIN), but in my experience i have never actually run into that
requirement.  either way, if and when we switch to pushing our metadata via
CLARIN, i would like it to be the case that existing opt-ins across norway
remain valid.  presumably keeping the SP identity unchanged should ensure
that, but again i would first want to get confirmation of that from Feide.

in principle i would be happy for CLARIN to publish our metadata, and if
need be i would of course also not mind you making necessary improvements
(or i could, of course, make those changes myself before pushing into the
CLARIN repository).  ideally, however, i feel our SP should generate
compliant and complete metadata natively, such that future updates will not
require us to remember and re-apply additions and changes that have been
made manually.

that ideal state of affairs may be out-of-reach, though.  yes, i will fix
the mailto: and logo issues.  but putting ‘FriendlyName’ and
‘isRequired=false’ on my attributes may turn out impossible.  the
SimpleSAMLphp configuration side of things looks like this:

        'attributes' => array('mail' => 'urn:oid:0.9.2342.19200300.100.1.3',
                              'eduPersonPrincipalName' =>
'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
                              'eduPersonTargetedID' =>
'urn:oid:1.3.6.1.4.1.5923.1.1.1.10'),
        'attributes.required' => array('urn:oid:0.9.2342.19200300.100.1.3'),
        'attributes.NameFormat' =>
'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',

—i am still looking for the right way of adding the EC information on my
end, but will soon be calling it a day :-).  in the meantime, i am happy to
observe that i got authentication against the CLARIN IdP to work for my SP,
so my immediate goal is at least satisfied.

god helg!  oe

**Comment by andmor-** [comment]
> in the meantime, i am happy to observe that i got authentication against the CLARIN IdP to work for my SP, so my immediate goal is at least satisfied.

Great! That is indeed the most important part :)

> before switching over from Feide to CLARIN as our metadata publisher, i would like to discuss this move with the Feide folks.

Or course! This has to be synchronized with FEIDE as we should make sure everything works after the change.

> Feide picks up information about a new SP, they announce it to all their customers. before users at another norwegian university actually get to authenticate (via Feide) for the service, their institution needs to consent. i would expect the same must be true for non-norwegian SPs (that support eduGAIN), but in my experience i have never actually run into that requirement. either way, if and when we switch to pushing our metadata via CLARIN, i would like it to be the case that existing opt-ins across norway remain valid. presumably keeping the SP identity unchanged should ensure that, but again i would first want to get confirmation of that from Feide.

This is exactly the case I mention about whitelisting (consent). I understand from what you wrote that Feide also works in this eduGAIN+whitelisting scheme.
I believe that they are already whitelisting all our SPs, but if not we should try that the whitelisting/consent is done on the `clarin-member` EC, rather than the `entityID`. This will ensure that the consent is given to all CLARIN SPs, as it happens in the other countries (and which also allows your SP to work when some IdP whitelists us elsewhere). 
Anyway this is another strong reason to closely synchronize this discussion with Feide!

> that ideal state of affairs may be out-of-reach, though. yes, i will fix the mailto: and logo issues. but putting ‘FriendlyName’ and ‘isRequired=false’ on my attributes may turn out impossible.

Then I would say we are good to go: I added `‘FriendlyName’ and ‘isRequired=false’` for the sake of clarity, they are not strictly needed so we don't mind if they are not there due to technical restrictions. So feel free to remove them on the `lap_clarino` branch.

Have a nice weekend,
André

**Comment by andmor-** [comment]
FYI I just received an important warning from the eduGAIN folks: the SP certificate will expire on the 30th of June. 
The online eduGAIN metadata validation tool (https://technical.edugain.org/validator) now reports 2 warnings:

```
Entities recommendations which failed:

    https://lap.clarino.uio.no/simplesaml/module.php/saml/sp/metadata.php/default-sp
    as SPSSODescriptor
        mdui:UIInfo found but no Logo element
        Signing and encryption certificates of this entity will expired in less than 31 days
```

**Comment by oepen** [comment]
thanks for the notification, andre,

yes, i have already received our new certificate ... to be installed in the
next few days!  at the same time, i hope to put my metadata improvements
into production (including a secure logo URL and mailto: prefixes on
contact emails)—and once that is done, i shall come back to pushing our
metadata into the CLARIN repository :-).

cheers, oe

**Comment by andmor-** [comment]
Please check the SAML x509 certificate. It is still expired on our version (same for Feide's and eduGAIN's). This can be seen using the metadata validation tool.

**Pull request closed without merging**
