### PR TITLE
Exchanged the DARIAH AAI connector, since DARIAH now works with a AAI…

### PR DESCRIPTION
**Pull request by martinhaase**
… proxy model. 
According to DFN Metadata there is now a new xmlns:remd="http://refeds.org/metadata", I just added it to the CLARIN Metadata. Feel free to remove it, together with the according contact type. 
Regards, Martin

### CODE REVIEW

**Comment by andmor-** [comment]
There should be no problem with the added extra contact.

This PR changes the SP `entityID` so it is equivalent to adding a new SP (and removing the old). When the change is done, all IdP's that were working for the old `entityID` SP will stop to do so and will start working only for the new one. So can I proceed with the change? What's the current status of the production instance?

**Comment by martinhaase** [comment]
This is the production instance, aaiproxy.de.dariah.eu. All DARIAH services will move behind it. We are aware that the instance will be treated as a new SP by IdPs. Do I understand it correctly that the SP we enter here is only for the CLARIN homeless IdP? We'll then enter this IdP's metadata at the Proxy, can you again give the link to it's metadata?

**Comment by andmor-** [comment]
No. The metadata will then be picked up by DFN-AAI who verifies it and if all is good pushes it to eduGAIN (but it comes from us initially). We also manually push it to the national federations which do not work well with eduGAIN (NL, CZ, BE...). In short this will be the metadata all IdPs will see. For more information on our metadata distribution process check:
https://www.clarin.eu/node/3313
https://trac.clarin.eu/wiki/ServiceProviderFederation#ChangingtheSAMLmetadataaboutSPFSPs (requires a clarin IdP account)

You can find the metadata of the CLARIN (homeless) IdP here:
https://infra.clarin.eu/aai/prod_md_about_clarin_erics_idp.xml

In general all the information (the answer to your questions and more) is either available or linked from here:
https://www.clarin.eu/content/service-provider-federation

So knowing this, my question remains: shall we push this change to DFN->eduGAIN and the other identity federations, straight away?

**Comment by martinhaase** [comment]
Aaah. So, no, please do not push aaiproxy.de.dariah.eu to  DFN and eduGAIN, it is already there. We only want this SP to connect to the CLARIN homeless IdP, this is why we entered it here.

**Comment by andmor-** [comment]
OK. Maybe we should schedule a call to see this. The metadata in the SPF in intended to be distributed the same way for all SPs. We cannot deal with the overhead of exceptions given the amount of SPs in the CLARIN SPF. I will discuss this internally but might take awhile due to the holiday period.
The CLARIN homeless IdP is intended to be used by CLARIN SPF members (who adhere to our workflow).

Also, do you know that this way:
- No IdP in The Netherlands will connect to your SP.
- Very few IdPs in Belgium and Czech Republic will connect. 
- Unless you have some other agreement in place, very few IdPs in Germany will connect, given Germany mesh+whitelists federation model.

For more info on the added value of having your metadata in the CLARIN SPF [check this comment](https://github.com/clarin-eric/SPF-SPs-metadata/pull/39#issuecomment-397646491)

**Comment by martinhaase** [comment]
Sure, but the aim is to do interoperability between DARIAH AAI and CLARIN AAI. We see these components:
* DARIAH Services authenticating with CLARIN IdPs - this is covered since both our proxy is in eduGAIN, and you are working hard to put your IdP in eduGAIN. Our proxy has CoCo and R&S enabled, which are the current standards DARIAH chose to follow.
* CLARIN services authenticating with DARIAH IdPs - this is covered since you are working hard to put these services in eduGAIN, and all DARIAH IdPs are in eduGAIN, including the DARIAH homeless IdP.
* DARIAH Services authenticating with the CLARIN homeless IdP - not yet covered, since your IdP is not in eduGAIN; this is all this pull request is about.

**Comment by andmor-** [comment]
OK since this is not really a CLARIN SPF SP and the metadata is only kept here due to the absence of a better place, I will proceed with the merge and make sure this is not pushed to DFN-AAI or eduGAIN.

Some remarks about the components:

> DARIAH Services authenticating with CLARIN IdPs - this is covered since both our proxy is in eduGAIN, and you are working hard to put your IdP in eduGAIN. Our proxy has CoCo and R&S enabled, which are the current standards DARIAH chose to follow.

This is only partially true. 
Keep in ind there are no "CLARIN IdPs" (apart from the homeless one). What we have is CLARIN countries. Their federations and institutions manage their IdPs which usually are not related to anything specific to CLARIN. All we do is to aggregate the metadata of the IdPs from these countries and republish it in a single file so our SPs can easily consume it.
In this scope, no user from the CLARIN country e.g. Netherlands will be able to use her own institution's IdP to login into DARIAH Services. Their IdPs are typically not in eduGAIN and when they are, they still require an explicit authorization from the IdP admin to connect to any SP for the first time.
CLARIN does not try in any way to change the way the national identity federations work with eduGAIN. Nor SURF (in this example) is willing to change their policy.

> CLARIN services authenticating with DARIAH IdPs - this is covered since you are working hard to put these services in eduGAIN, and all DARIAH IdPs are in eduGAIN, including the DARIAH homeless IdP.

Under which registration authority is he DARIAH homeless IdP published on eduGAIN? It could be that we are not importing it into our feed.
Assuming all DARIAH IdPs consume all CLARIN SPF metadata via eduGAIN there is still a problem: if a  "DARIAH IdP" uses whitelisting (very typical in e.g. Germany) or is member of an hub and spoke federation (e.g. the Netherlands) this won't work for that IdP.
Also where are these IdPs located? By default, our SPs only consume eduGAIN IdP metadata from CLARIN countries.

> DARIAH Services authenticating with the CLARIN homeless IdP - not yet covered, since your IdP is not in eduGAIN; this is all this pull request is about.

Merging...

**Comment by martinhaase** [comment]
Thanks for merging! However the metadata of our proxy do not seem to be there yet, I just (2018-07-30 09:37:28) had a try choosing "CLARIN ERIC" when logging in to https://auth.de.dariah.eu/cgi-bin/selfservice/ldapportal.pl, and got a:

> eu.unicore.samly2.exceptions.SAMLRequesterException: Issuer is not among trusted: https://aaiproxy.de.dariah.eu/sp

....could you check once more?

**Comment by andmor-** [comment]
It seems that there was a refresh problem in on Unity idm. I did a manual refresh and it should work now. Can you please check?
Our IdP consumes the metadata from this URL: https://infra.clarin.eu/aai/md_about_spf_sps.xml

**Comment by martinhaase** [comment]
Yeah, I'm one step further, looks good. Could you test the login (I do not have one)? Just select "CLARIN ERIC" after you hit "Login" at https://auth.de.dariah.eu/cgi-bin/selfservice/ldapportal.pl - it should actually find your old shadow account from January

**Comment by andmor-** [comment]
Seems to be working fine and found my account.

**Comment by martinhaase** [comment]
That is triple great! Thanks for all! Have a nice week then!

**Pull request merged**
