### PR TITLE
Added RU CLST to metadata

### PR DESCRIPTION
**Pull request by Woseseltops**

### CODE REVIEW

**Comment by andmor-** [comment]
OK copy/paste error from my side: can you remove the 1st `<Extensions>` block (the old one was forgotten there, so there are 2 and should be just 1) and update the pull request?

**Comment by andmor-** [comment]
Also `contactType=` must be the 3 types of contacts "administrative" (already there x3), "support", "technical"

**Comment by Woseseltops** [comment]
Yeaeah @andmor- it passed!

giphy

**Comment by andmor-** [comment]
Validation is good but it is going to fail in the next step (QA assessment): now I have 2x `contactType="technical"` 1x `contactType="support"`

We need: 1x `contactType="technical"`, 1x `contactType="support"` 1x `contactType="administrative"`

**Comment by Woseseltops** [comment]
This better @andmor- ?

**Comment by andmor-** [comment]
QA report looks good to me:
- the 2 warnings about missing information in German do not apply here
- the English description is a bit long but should be fine IMHO

I will now merge this into our production feed and start the propagation. You can follow the countries/federations that already imported your metadata [here](https://centres.clarin.eu/spf) (a new entry will appear soon for the RU SP)

**Comment by andmor-** [comment]
Wait: is the privacy statement URL right? Isn't that ours?

**Comment by andmor-** [comment]
If not, just make a new PR with the updated privacy statement URL

**Comment by Woseseltops** [comment]
Whoops sorry, I've fixed it. Not sure if I need to make a new RP now?

**Comment by andmor-** [comment]
Either that or just pass me the new URL here. I will put it in place

**Comment by Woseseltops** [comment]
This is the URL https://applejack.science.ru.nl/privacy.html

**Comment by andmor-** [comment]
Merged to production in #73 
Now we wait! And follow progress: https://centres.clarin.eu/spf

**Pull request merged**
